# syntax=docker/dockerfile:1.7

# Development-only compatibility build for
# naughtont3/slurm-docker-cluster@8c8065cbebb475a512a66cabff9aceda5f2c57b0.
# Adapted from the MIT-licensed Dockerfile by Giovanni Torres and Thomas
# Naughton. The source repository's LICENSE notice remains authoritative.

FROM rockylinux:8

LABEL org.opencontainers.image.source="https://github.com/naughtont3/slurm-docker-cluster" \
      org.opencontainers.image.revision="8c8065cbebb475a512a66cabff9aceda5f2c57b0" \
      org.opencontainers.image.title="QHPC Slurm development test cluster" \
      org.opencontainers.image.description="Development-only Slurm Docker cluster for QHPC scheduler tests"

RUN --mount=type=secret,id=qhpc_build_ca \
    set -eux \
    && if [ -s /run/secrets/qhpc_build_ca ]; then \
         cp /run/secrets/qhpc_build_ca \
            /etc/pki/ca-trust/source/anchors/qhpc-build-ca.pem; \
         update-ca-trust; \
       fi \
    && yum makecache \
    && yum -y update \
    && yum -y install dnf-plugins-core epel-release \
    && yum config-manager --set-enabled powertools \
    && yum -y install \
       bash-completion \
       bzip2 \
       curl \
       gcc \
       gcc-c++ \
       git \
       gnupg \
       http-parser-devel \
       json-c-devel \
       libjwt-devel \
       libyaml-devel \
       make \
       mariadb-devel \
       mariadb-server \
       munge \
       munge-devel \
       openssl \
       perl \
       procps-ng \
       psmisc \
       python3 \
       vim-enhanced \
       wget \
    && yum clean all \
    && rm -rf /var/cache/yum

ARG GOSU_VERSION=1.17
ARG TARGETARCH

RUN set -eux \
    && case "$TARGETARCH" in amd64|arm64) ;; *) exit 64 ;; esac \
    && wget -O /usr/local/bin/gosu \
       "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${TARGETARCH}" \
    && wget -O /usr/local/bin/gosu.asc \
       "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${TARGETARCH}.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && curl -fsSL \
       "https://keys.openpgp.org/pks/lookup?op=get&search=0xB42F6819007F00F88E364FD4036A9C25BF357DD4" \
       | gpg --batch --import \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

ARG SLURM_TAG

RUN set -eux \
    && git clone --branch "$SLURM_TAG" --single-branch --depth=1 \
       https://github.com/SchedMD/slurm.git \
    && cd slurm \
    && ./configure \
       --enable-debug \
       --prefix=/usr \
       --sysconfdir=/etc/slurm \
       --with-mysql_config=/usr/bin \
       --libdir=/usr/lib64 \
       --with-http-parser=/usr \
       --with-yaml=/usr \
       --with-jwt=/usr \
    && make -j"$(nproc)" install \
    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh \
       /etc/profile.d/slurm_completion.sh \
    && cd / \
    && rm -rf slurm \
    && groupadd -r --gid=990 slurm \
    && useradd -r -g slurm --uid=990 slurm \
    && mkdir -p \
       /etc/sysconfig/slurm \
       /var/spool/slurmd \
       /var/run/slurmd \
       /var/run/slurmdbd \
       /var/lib/slurmd \
       /var/log/slurm \
       /data \
    && touch \
       /var/lib/slurmd/node_state \
       /var/lib/slurmd/front_end_state \
       /var/lib/slurmd/job_state \
       /var/lib/slurmd/resv_state \
       /var/lib/slurmd/trigger_state \
       /var/lib/slurmd/assoc_mgr_state \
       /var/lib/slurmd/assoc_usage \
       /var/lib/slurmd/qos_usage \
       /var/lib/slurmd/fed_mgr_state \
    && chown -R slurm:slurm /var/lib/slurm* /var/log/slurm /var/run/slurm* \
    && /sbin/create-munge-key \
    && rm -f /etc/pki/ca-trust/source/anchors/qhpc-build-ca.pem \
    && update-ca-trust

COPY cgroup.conf /etc/slurm/cgroup.conf
COPY slurm.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf
COPY rest.conf /etc/slurm/rest.conf
COPY gres.conf /etc/slurm/gres.conf

RUN set -eux \
    && openssl rand -hex 32 > /etc/slurm/jwt.key \
    && chown slurm:slurm \
       /etc/slurm/slurm.conf \
       /etc/slurm/jwt.key \
       /etc/slurm/rest.conf \
       /etc/slurm/gres.conf \
       /etc/slurm/slurmdbd.conf \
    && chmod 600 /etc/slurm/jwt.key /etc/slurm/slurmdbd.conf \
    && useradd -r -g users --uid=1010 -m -c "QHPC test user" qhpctest

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["slurmdbd"]
