FROM rockylinux/rockylinux@sha256:b86cb4305db4c29abb1e3a1257fefccc184b5e4a94378e02844b340845ef9460

ARG QFW_CLUSTER_REVISION=eeb42e601383f3d33020f823d4a387ef30b9dd7d
ARG QFW_SOURCE_REVISION=38f54cde6c629cc3ede38bbf7605d416d4e82608
ARG QFW_SLURM_SOURCE_REVISION=0c3694bb82a3413a4aaee3b2944db1b4dd346beb

LABEL org.opencontainers.image.source="https://github.com/openQSE/QFw-SLURM-Cluster" \
      org.opencontainers.image.revision="${QFW_CLUSTER_REVISION}" \
      org.opencontainers.image.title="QHPC OpenQSE QFw Slurm compatibility image" \
      org.opencontainers.image.description="Pinned development-only OpenQSE QFw Slurm simulation" \
      org.qhpc.qfw.revision="${QFW_SOURCE_REVISION}" \
      org.qhpc.qfw-slurm.revision="${QFW_SLURM_SOURCE_REVISION}" \
      org.label-schema.docker.cmd="docker compose up -d" \
      maintainer="QSC Software Thrust"

# Optional office TLS interception is admitted only through a public CA file
# supplied by `eqo slurm-test-cluster prepare --build-ca`. Empty is valid.
COPY qhpc-build-ca.pem /tmp/qhpc-build-ca.pem
RUN set -ex \
  && if [ -s /tmp/qhpc-build-ca.pem ]; then \
       install -m 0644 /tmp/qhpc-build-ca.pem \
         /etc/pki/ca-trust/source/anchors/qhpc-build-ca.pem; \
       update-ca-trust; \
     fi \
  && rm -f /tmp/qhpc-build-ca.pem \
    && dnf makecache \
    && dnf -y install \
       dnf-plugins-core-4.7.0-10.el10.noarch \
       epel-release-10-7.el10_1.noarch \
    && dnf config-manager --set-enabled crb \
    && dnf -y --setopt=install_weak_deps=False install \
       autoconf-2.71-13.el10.noarch \
       automake-1.16.5-20.el10.noarch \
       bison-3.8.2-9.el10.x86_64 \
       bzip2-devel-1.0.8-25.el10.x86_64 \
       diffutils-3.10-8.el10.x86_64 \
       expat-devel-2.7.3-1.el10_2.3.x86_64 \
       file-5.45-9.el10.x86_64 \
       flex-2.6.4-19.el10.x86_64 \
       wget-1.24.5-8.el10_2.x86_64 \
       bzip2-1.0.8-25.el10.x86_64 \
       curl-8.12.1-4.el10_2.4.x86_64 \
       findutils-4.10.0-5.el10.x86_64 \
       gdbm-devel-1.23-14.el10.x86_64 \
       gzip-1.13-4.el10_2.x86_64 \
       libffi-devel-3.4.4-10.el10.x86_64 \
       libcurl-devel-8.12.1-4.el10_2.4.x86_64 \
       libtool-2.4.7-14.el10.x86_64 \
       lua-5.4.6-7.el10.x86_64 \
       lua-devel-5.4.6-7.el10.x86_64 \
       m4-1.4.19-11.el10.x86_64 \
       ncurses-devel-6.4-15.20240127.el10_1.x86_64 \
       openssl-3.5.8-1.el10_2.x86_64 \
       openssl-devel-3.5.8-1.el10_2.x86_64 \
       openssh-clients-9.9p1-25.el10_2.rocky.0.1.x86_64 \
       perl-5.40.2-515.el10_2.x86_64 \
       patch-2.7.6-26.el10.x86_64 \
       libuuid-devel-2.40.2-18.el10.x86_64 \
       readline-devel-8.2-11.el10.x86_64 \
       sqlite-devel-3.46.1-6.el10_2.x86_64 \
       tar-1.35-13.el10_2.x86_64 \
       tk-devel-8.6.13-5.el10.x86_64 \
       gcc-14.3.1-4.4.el10.x86_64 \
       gcc-c++-14.3.1-4.4.el10.x86_64 \
       gcc-gfortran-14.3.1-4.4.el10.x86_64 \
       git-2.52.0-1.el10.x86_64 \
       make-4.4.1-9.el10.x86_64 \
       munge-0.5.15-11.el10_1.x86_64 \
       munge-devel-0.5.15-11.el10_1.x86_64 \
       python3-devel-3.12.14-1.el10_2.x86_64 \
       python3-pip-23.3.2-11.el10_2.noarch \
       python3-3.12.14-1.el10_2.x86_64 \
       mariadb-server-10.11.18-1.el10_2.x86_64 \
       mariadb-devel-10.11.18-1.el10_2.x86_64 \
       psmisc-23.6-8.el10.x86_64 \
       bash-completion-2.11-16.el10.noarch \
       xz-devel-5.6.2-4.el10_2.1.x86_64 \
       vim-enhanced-9.1.083-9.el10_2.20.x86_64 \
       json-c-devel-0.18-3.el10.x86_64 \
       libjwt-devel-2.1.2-1.el10_1.x86_64 \
       libyaml-devel-0.2.5-16.el10.x86_64 \
       zlib-ng-compat-devel-2.2.3-3.el10_1.x86_64 \
       environment-modules-5.6.1-2.el10.x86_64 \
       cmake-3.31.8-1.el10.x86_64 \
       openblas-devel-0.3.29-2.el10.x86_64 \
       swig-4.3.0-4.el10.x86_64 \
       ninja-build-1.11.1-9.el10.x86_64 \
       pkgconf-pkg-config-2.1.0-3.el10.x86_64 \
       ca-certificates-2025.2.80_v9.0.305-102.el10.noarch \
    && dnf clean all \
    && rm -rf /var/cache/yum

ARG HTTP_PARSER_REVISION=2343fd6b5214b2ded2cdcf76de2bf60903bb90cd
ARG HTTP_PARSER_PREFIX=/opt/qfw/http-parser

RUN set -ex \
    && git init /tmp/http-parser \
    && git -C /tmp/http-parser remote add origin https://github.com/nodejs/http-parser.git \
    && git -C /tmp/http-parser fetch --depth=1 origin "${HTTP_PARSER_REVISION}" \
    && git -C /tmp/http-parser checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/http-parser rev-parse HEAD)" = "${HTTP_PARSER_REVISION}" \
    && cd /tmp/http-parser \
    && make -j"$(nproc)" package library \
    && mkdir -p "${HTTP_PARSER_PREFIX}/include" "${HTTP_PARSER_PREFIX}/lib" \
    && cp http_parser.h "${HTTP_PARSER_PREFIX}/include/" \
    && cp libhttp_parser.a "${HTTP_PARSER_PREFIX}/lib/" \
    && cp libhttp_parser.so* "${HTTP_PARSER_PREFIX}/lib/" \
    && rm -rf /tmp/http-parser

ARG GOSU_VERSION=1.17
ARG GOSU_SHA256=bbc4136d03ab138b1ad66fa4fc051bafc6cc7ffae632b069a53657279a450de3

RUN set -ex \
    && curl --proto '=https' --tlsv1.2 -fsSL \
       -o /usr/local/bin/gosu \
       "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" \
    && echo "${GOSU_SHA256}  /usr/local/bin/gosu" | sha256sum -c - \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

ARG SLURM_REVISION=91f6d444e368c96e38c9dc0be0c637737bb501d5
ARG GCC13_ROOT=/usr
ARG LIBFABRIC_REVISION=413a2d315ee8485488fb4fdcc0012e029f570b6b
ARG LIBFABRIC_PREFIX=/opt/qfw/libfabric
ARG OMPI_REVISION=b79100b3fbbf45b3c6ed82a6b67b6346f8cfdc41
ARG OMPI_PREFIX=/opt/qfw/openmpi
ARG OSU_OMB_VERSION=7.5.2
ARG OSU_OMB_SHA256=618de3d0b1122f73a9229177d2da1e5cd62e431190580cb915f2605849cbbbdc
ARG OSU_OMB_PREFIX=/opt/qfw/osu-micro-benchmarks

RUN set -x \
    && git init /tmp/slurm \
    && git -C /tmp/slurm remote add origin https://github.com/SchedMD/slurm.git \
    && git -C /tmp/slurm fetch --depth=1 origin "${SLURM_REVISION}" \
    && git -C /tmp/slurm checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/slurm rev-parse HEAD)" = "${SLURM_REVISION}" \
    && pushd /tmp/slurm \
    && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm \
        --with-mysql_config=/usr/bin  --libdir=/usr/lib64 \
        --with-http-parser="${HTTP_PARSER_PREFIX}" --with-yaml=/usr --with-jwt=/usr \
    && make install \
    && test -x /usr/lib64/slurm/job_submit_lua.so \
    && test -x /usr/lib64/slurm/burst_buffer_lua.so \
    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh \
    && sed -i '1a case $- in *i*) ;; *) return 0 2>/dev/null || exit 0 ;; esac' \
        /etc/profile.d/slurm_completion.sh \
    && popd \
    && rm -rf /tmp/slurm \
    && groupadd -r --gid=990 slurm \
    && useradd -r -g slurm --uid=990 slurm \
    && mkdir /etc/sysconfig/slurm \
        /var/spool/slurmd \
        /var/run/slurmd \
        /var/run/slurmdbd \
        /var/lib/slurmd \
        /var/log/slurm \
        /data \
    && touch /var/lib/slurmd/node_state \
        /var/lib/slurmd/front_end_state \
        /var/lib/slurmd/job_state \
        /var/lib/slurmd/resv_state \
        /var/lib/slurmd/trigger_state \
        /var/lib/slurmd/assoc_mgr_state \
        /var/lib/slurmd/assoc_usage \
        /var/lib/slurmd/qos_usage \
        /var/lib/slurmd/fed_mgr_state \
    && chown -R slurm:slurm /var/*/slurm* \
    && install -d -o munge -g munge -m 0700 /etc/munge

RUN set -ex \
    && export PATH="${GCC13_ROOT}/bin:${PATH}" \
    && export LD_LIBRARY_PATH="${GCC13_ROOT}/lib64:${LD_LIBRARY_PATH}" \
    && export CC="${GCC13_ROOT}/bin/gcc" \
    && export CXX="${GCC13_ROOT}/bin/g++" \
    && export FC="${GCC13_ROOT}/bin/gfortran" \
    && git init /tmp/libfabric \
    && git -C /tmp/libfabric remote add origin https://github.com/ofiwg/libfabric.git \
    && git -C /tmp/libfabric fetch --depth=1 origin "${LIBFABRIC_REVISION}" \
    && git -C /tmp/libfabric checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/libfabric rev-parse HEAD)" = "${LIBFABRIC_REVISION}" \
    && cd /tmp/libfabric \
    && ./autogen.sh \
    && ./configure --prefix="${LIBFABRIC_PREFIX}" CC="${CC}" CXX="${CXX}" FC="${FC}" \
    && make -j"$(nproc)" all \
    && make install \
    && rm -rf /tmp/libfabric

RUN set -ex \
    && export PATH="${GCC13_ROOT}/bin:${PATH}" \
    && export LD_LIBRARY_PATH="${GCC13_ROOT}/lib64:${LD_LIBRARY_PATH}" \
    && export CC="${GCC13_ROOT}/bin/gcc" \
    && export CXX="${GCC13_ROOT}/bin/g++" \
    && export FC="${GCC13_ROOT}/bin/gfortran" \
    && export PKG_CONFIG_PATH="${LIBFABRIC_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}" \
    && export CPPFLAGS="-I${LIBFABRIC_PREFIX}/include ${CPPFLAGS}" \
    && export LDFLAGS="-L${LIBFABRIC_PREFIX}/lib ${LDFLAGS}" \
    && git init /tmp/ompi \
    && git -C /tmp/ompi remote add origin https://github.com/open-mpi/ompi.git \
    && git -C /tmp/ompi fetch --depth=1 origin "${OMPI_REVISION}" \
    && git -C /tmp/ompi checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/ompi rev-parse HEAD)" = "${OMPI_REVISION}" \
    && git -C /tmp/ompi submodule update --init --recursive \
    && cd /tmp/ompi \
    && ./autogen.pl \
    && ./configure --prefix="${OMPI_PREFIX}" --with-libfabric="${LIBFABRIC_PREFIX}" --with-slurm CC="${CC}" CXX="${CXX}" FC="${FC}" \
    && make -j"$(nproc)" all \
    && make install \
    && rm -rf /tmp/ompi

RUN set -ex \
    && export PATH="${OMPI_PREFIX}/bin:${PATH}" \
    && export LD_LIBRARY_PATH="${OMPI_PREFIX}/lib:${LIBFABRIC_PREFIX}/lib:${LD_LIBRARY_PATH}" \
    && cd /tmp \
    && curl --proto '=https' --tlsv1.2 -fsSL \
        -o osu-micro-benchmarks-${OSU_OMB_VERSION}.tar.gz \
        https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-${OSU_OMB_VERSION}.tar.gz \
    && echo "${OSU_OMB_SHA256}  osu-micro-benchmarks-${OSU_OMB_VERSION}.tar.gz" | sha256sum -c - \
    && tar --no-same-owner -xzf osu-micro-benchmarks-${OSU_OMB_VERSION}.tar.gz \
    && cd osu-micro-benchmarks-${OSU_OMB_VERSION} \
    && ./configure CC=mpicc CXX=mpicxx --prefix="${OSU_OMB_PREFIX}" \
    && make -j"$(nproc)" all \
    && make install \
    && rm -rf /tmp/osu-micro-benchmarks-${OSU_OMB_VERSION} /tmp/osu-micro-benchmarks-${OSU_OMB_VERSION}.tar.gz

ARG QFW_BUILD_JOBS=4

# The image contains a complete release installation. A checkout mounted under
# QFW_BASE remains an optional developer override built by do_qfw_build.sh.
ARG QFW_REPOSITORY=https://github.com/openQSE/QFw.git
ARG QFW_REF=38f54cde6c629cc3ede38bbf7605d416d4e82608
ARG QFW_DEFW_REPOSITORY=
ARG QFW_SLURM_REPOSITORY=https://github.com/openQSE/qfw-slurm.git
ARG QFW_SLURM_REF=0c3694bb82a3413a4aaee3b2944db1b4dd346beb
ARG QFW_IMAGE_SOURCE=/tmp/qfw-source
ARG QFW_IMAGE_BUILD=/tmp/qfw-build
ARG QFW_IMAGE_PREFIX=/opt/openqse/qfw
ARG QFW_IMAGE_VENV=/opt/openqse/qfw-venv
ARG QFW_SLURM_SOURCE=/tmp/qfw-slurm-source
ARG QFW_SLURM_BUILD=/tmp/qfw-slurm-build
ARG QFW_SLURM_PREFIX=/opt/openqse/qfw-slurm
ARG NWQSIM_PREFIX=/opt/openqse/nwqsim
ARG TNQVM_PREFIX=/opt/openqse/tnqvm
ARG SIMULATOR_WORK_ROOT=/tmp/qfw-simulator-build

ENV QFW_BASE=/workspace/qfw-container-base \
    QFW_BUILD_JOBS=${QFW_BUILD_JOBS}

ENV PATH=${OMPI_PREFIX}/bin:${LIBFABRIC_PREFIX}/bin:${PATH}

ENV LD_LIBRARY_PATH=${OMPI_PREFIX}/lib:${LIBFABRIC_PREFIX}/lib

# ----------------------------------------------------------------------
# QRMI / QDMI shim dependencies
#
# Lower-level interface libraries the QFw front-end shim will route to.
# ----------------------------------------------------------------------

ARG RUST_VERSION=1.91.0
ARG RUSTUP_VERSION=1.28.2
ARG RUSTUP_SHA256=20a06e644b0d9bd2fbdbfd52d42540bdde820ea7df86e92e533c073da0cdd43c
ENV CARGO_HOME=/opt/qfw/rust/cargo \
    RUSTUP_HOME=/opt/qfw/rust/rustup
RUN set -ex \
    && mkdir -p "${CARGO_HOME}" "${RUSTUP_HOME}" \
    && curl --proto '=https' --tlsv1.2 -fsSL \
        -o /tmp/rustup-init \
        "https://static.rust-lang.org/rustup/archive/${RUSTUP_VERSION}/x86_64-unknown-linux-gnu/rustup-init" \
    && echo "${RUSTUP_SHA256}  /tmp/rustup-init" | sha256sum -c - \
    && chmod 0755 /tmp/rustup-init \
    && /tmp/rustup-init -y --no-modify-path --profile minimal \
        --default-toolchain "${RUST_VERSION}" \
    && rm -f /tmp/rustup-init \
    && chmod -R a+rwX /opt/qfw/rust
ENV PATH=${CARGO_HOME}/bin:${PATH}

# QRMI: build the C library (libqrmi.so + qrmi.h) and the SLURM SPANK plugin
# from source, then install the matching Python bindings from PyPI.
#
# A single QRMI_VERSION drives both the git tag (for the C library and the
# SPANK plugin's QRMI_ROOT) and the PyPI release (for the Python bindings),
# so the C ABI loaded by C/C++ shim consumers matches the bindings loaded
# into the QFw venv.
#
# NOTE: upstream changed tag convention around the 0.14 release from
# "vX.Y.Z" to "X.Y.Z" (no leading v). Use the unprefixed form for any
# release >= 0.14.0; older releases need the "v" prefix.
# QRMI 0.24.4 with spank-plugins 0.11.0. The plugin links the locally-cloned
# QRMI via -DQRMI_ROOT, so it must be built against whatever QRMI_VERSION says.
# Bumping either ARG invalidates the whole RUN layer below, which rebuilds the
# plugin from scratch, as QRMI's release announcement asks for.
#
# 0.24.4 brings the default QuantumResource trait implementations (upstream
# issue #236, which cites the openQSE QRMI/QDMI analysis report as motivation).
# A vendor now only overrides what its backend supports and the rest return
# UnsupportedFunction. For IQM, acquire() still returns a generated UUID without
# contacting the provider, but it now also logs
#   WARN qrmi: acquiring resource is not implemented by this resource(...)
# That warning arrives with no RUST_LOG set, because the Rust-to-Python log
# bridge is level-filtered rather than off by default. WARN passes, DEBUG does
# not. So the silent no-op is now an announced one.
#
# THE HEALTH-STATUS GAP IS STILL OPEN AND STILL DOES NOT AFFECT US. 0.24.3 was
# announced as fixing is_accessible() against old IQM servers. It fixes one
# meaning of old, a server that nests health but omits operational, which now
# defaults to "online". It does NOT fix a server whose response is genuinely
# flat, because the health field itself is still required with no default and
# no alias. THE ORNL q20 IS STILL FLAT, verified 2026-09-08:
#   {"healthy": true, "updated_at": "..."}
# so is_accessible() still raises there. The error moved rather than went away,
# from missing field `operational` on 0.24.0 to missing field `health` on
# 0.24.4. Reported upstream.
#
# QFw is unaffected because it never calls is_accessible(). That call is absent
# from QrmiDriver.CAPABILITIES and from services/ entirely. target() was
# re-verified against the q20 on 0.24.4 and returns 20 qubits normally.
#
# IF is_accessible() IS EVER WIRED INTO THE SHIM, this pin becomes a live
# problem until either ORNL's IQM API or QRMI's health model is updated. That
# is the trigger to revisit.
#
# 0.24.0 also added typed errors. The new Python exceptions all subclass
# RuntimeError, which is what the drivers already catch, so that half is purely
# additive.
#
# Earlier context worth keeping: 0.23.0 renamed the IBM Qiskit Runtime Service
# resource type to IBM Quantum Compute Service (QRMI_IBM_QRS_ -> QRMI_IBM_QCS_,
# legacy accepted until 2026-11-21), and 0.22.0 added the static architecture to
# target() plus Rust-to-Python log bridging and a GIL deadlock fix. The renames
# do not reach QFw, which opens ResourceType.IQMServer and reads
# {backend}_QRMI_IQM_ISA_*. The static architecture does: it arrives as a list,
# and services/svc_lib_qpm/drivers/qrmi_driver.py unwraps it before handing it
# to qhw-iqm.
ARG QRMI_REPO=https://github.com/qiskit-community/qrmi.git
ARG QRMI_VERSION=0.24.4
ARG QRMI_REVISION=cd3852c49a551cfe9c8e16c689ef99d082f00675
ARG QRMI_PREFIX=/opt/qfw/qrmi
ARG QRMI_SPANK_REPO=https://github.com/qiskit-community/spank-plugins.git
ARG QRMI_SPANK_REVISION=5c9439608f3aef4e1cdf2eaef022aa45b9b88fc9
RUN set -ex \
    && git init /tmp/qrmi \
    && git -C /tmp/qrmi remote add origin "${QRMI_REPO}" \
    && git -C /tmp/qrmi fetch --depth=1 origin "${QRMI_REVISION}" \
    && git -C /tmp/qrmi checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/qrmi rev-parse HEAD)" = "${QRMI_REVISION}" \
    && cd /tmp/qrmi \
    && cargo build --locked --release --lib \
    && mkdir -p "${QRMI_PREFIX}/lib" "${QRMI_PREFIX}/include" \
    && cp target/release/libqrmi.so "${QRMI_PREFIX}/lib/" \
    && (cp target/release/libqrmi.a "${QRMI_PREFIX}/lib/" 2>/dev/null || true) \
    && cp qrmi.h "${QRMI_PREFIX}/include/" \
    && git init /tmp/spank-plugins \
    && git -C /tmp/spank-plugins remote add origin "${QRMI_SPANK_REPO}" \
    && git -C /tmp/spank-plugins fetch --depth=1 origin \
        "${QRMI_SPANK_REVISION}" \
    && git -C /tmp/spank-plugins checkout --detach FETCH_HEAD \
    && test "$(git -C /tmp/spank-plugins rev-parse HEAD)" = \
        "${QRMI_SPANK_REVISION}" \
    && cd /tmp/spank-plugins/plugins/spank_qrmi \
    && cmake -S . -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DQRMI_ROOT=/tmp/qrmi \
    && cmake --build build \
    && install -d /usr/lib64/slurm \
    && find build -maxdepth 3 -name '*.so' -exec \
        install -m 0755 {} /usr/lib64/slurm/ \; \
    && rm -rf /tmp/qrmi /tmp/spank-plugins

# Obtain QFw solely as the versioned source for the independent simulator
# builders and the official QFw installation. QFw's CMake install does not
# invoke either simulator builder.
ARG QFW_SOURCE_REVISION
COPY qfw-dependency-pins.patch /tmp/qfw-dependency-pins.patch
RUN set -ex \
    && git init "${QFW_IMAGE_SOURCE}" \
    && git -C "${QFW_IMAGE_SOURCE}" remote add origin "${QFW_REPOSITORY}" \
    && git -C "${QFW_IMAGE_SOURCE}" fetch --depth=1 origin "${QFW_REF}" \
    && git -C "${QFW_IMAGE_SOURCE}" switch --detach FETCH_HEAD \
    && test "$(git -C "${QFW_IMAGE_SOURCE}" rev-parse HEAD)" = \
        "${QFW_SOURCE_REVISION}" \
    && if [ -n "${QFW_DEFW_REPOSITORY}" ]; then \
        git -C "${QFW_IMAGE_SOURCE}" config submodule.DEFw.url \
            "${QFW_DEFW_REPOSITORY}"; \
       fi \
    && git -C "${QFW_IMAGE_SOURCE}" \
        -c url.https://github.com/.insteadOf=git@github.com: \
        submodule update --init --recursive \
    && git -C "${QFW_IMAGE_SOURCE}" apply /tmp/qfw-dependency-pins.patch \
    && rm -f /tmp/qfw-dependency-pins.patch

COPY requirements.qhpc-build.lock /tmp/requirements.qhpc-build.lock
COPY requirements.qhpc.lock /tmp/requirements.qhpc.lock
RUN set -ex \
    && python3 -m venv "${QFW_IMAGE_VENV}" \
    && "${QFW_IMAGE_VENV}/bin/python" -m pip install \
        --require-hashes -r /tmp/requirements.qhpc-build.lock \
    && "${QFW_IMAGE_VENV}/bin/python" -m pip install \
        --require-hashes --no-build-isolation -r /tmp/requirements.qhpc.lock \
    && rm -f /tmp/requirements.qhpc-build.lock

RUN set -ex \
    && "${QFW_IMAGE_SOURCE}/tools/dependencies/nwqsim/build.sh" \
        --work-dir "${SIMULATOR_WORK_ROOT}/nwqsim" \
        --prefix "${NWQSIM_PREFIX}" \
        --jobs "${QFW_BUILD_JOBS}" \
        --rocm off \
    && test -x "${NWQSIM_PREFIX}/bin/circuit_runner.nwqsim"

ARG BOOST_VERSION=1.75.0
ARG BOOST_SHA256=953db31e016db7bb207f11432bef7df100516eeb746843fa0486a222e3fd49cb
RUN set -ex \
    && curl --proto '=https' --tlsv1.2 -fsSL \
        -o /tmp/boost_1_75_0.tar.bz2 \
        "https://archives.boost.io/release/${BOOST_VERSION}/source/boost_1_75_0.tar.bz2" \
    && echo "${BOOST_SHA256}  /tmp/boost_1_75_0.tar.bz2" | sha256sum -c - \
    && "${QFW_IMAGE_SOURCE}/tools/dependencies/tnqvm/build.sh" \
        --work-dir "${SIMULATOR_WORK_ROOT}/tnqvm" \
        --prefix "${TNQVM_PREFIX}" \
        --mpi-prefix "${OMPI_PREFIX}" \
        --python "${QFW_IMAGE_VENV}/bin/python" \
        --jobs "${QFW_BUILD_JOBS}" \
        --rocm off \
    && test -x "${TNQVM_PREFIX}/bin/circuit_runner.tnqvm" \
    && test -f "${TNQVM_PREFIX}/xacc/plugins/libtnqvm.so" \
    && rm -f /tmp/boost_1_75_0.tar.bz2

RUN set -ex \
    && PATH="${QFW_IMAGE_VENV}/bin:${PATH}" cmake \
        -S "${QFW_IMAGE_SOURCE}" \
        -B "${QFW_IMAGE_BUILD}" \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX="${QFW_IMAGE_PREFIX}" \
        -DQFW_BUILD_BUNDLED_DEFW=ON \
    && cmake --build "${QFW_IMAGE_BUILD}" \
        --parallel "${QFW_BUILD_JOBS}" \
    && cmake --install "${QFW_IMAGE_BUILD}" \
    && test -x "${QFW_IMAGE_PREFIX}/bin/qfw-activate" \
    && cp /tmp/requirements.qhpc.lock \
        "${QFW_IMAGE_PREFIX}/share/requirements.qhpc.lock" \
    && rm -f /tmp/requirements.qhpc.lock \
    && rm -rf "${QFW_IMAGE_SOURCE}" "${QFW_IMAGE_BUILD}" \
        "${SIMULATOR_WORK_ROOT}"

ARG QFW_SLURM_SOURCE_REVISION
RUN set -ex \
    && git init "${QFW_SLURM_SOURCE}" \
    && git -C "${QFW_SLURM_SOURCE}" remote add origin \
        "${QFW_SLURM_REPOSITORY}" \
    && git -C "${QFW_SLURM_SOURCE}" fetch --depth=1 origin \
        "${QFW_SLURM_REF}" \
    && git -C "${QFW_SLURM_SOURCE}" switch --detach FETCH_HEAD \
    && test "$(git -C "${QFW_SLURM_SOURCE}" rev-parse HEAD)" = \
        "${QFW_SLURM_SOURCE_REVISION}" \
    && "${QFW_IMAGE_VENV}/bin/python" -m pip install \
        --no-build-isolation --no-deps "${QFW_SLURM_SOURCE}" \
    && cmake -S "${QFW_SLURM_SOURCE}" -B "${QFW_SLURM_BUILD}" \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX="${QFW_SLURM_PREFIX}" \
        -DPython3_EXECUTABLE="${QFW_IMAGE_VENV}/bin/python" \
    && cmake --build "${QFW_SLURM_BUILD}" \
        --parallel "${QFW_BUILD_JOBS}" \
    && install -d -o munge -g munge -m 0700 /etc/munge /var/log/munge \
    && install -d -o munge -g munge -m 0755 /run/munge \
    && dd if=/dev/urandom of=/etc/munge/munge.key bs=1024 count=1 \
        status=none \
    && chown munge:munge /etc/munge/munge.key \
    && chmod 0400 /etc/munge/munge.key \
    && gosu munge /usr/sbin/munged \
    && ctest --test-dir "${QFW_SLURM_BUILD}" --output-on-failure \
    && pkill -u munge munged \
    && rm -f /etc/munge/munge.key /run/munge/munge.pid \
        /run/munge/munge.socket.2 \
    && cmake --install "${QFW_SLURM_BUILD}" \
    && install -d -m 0755 /usr/local/share/man \
    && cp -a "${QFW_SLURM_PREFIX}/share/man/." /usr/local/share/man/ \
    && install -o root -g root -m 0755 \
        "${QFW_SLURM_PREFIX}/lib64/slurm/spank_quantum.so" \
        /usr/lib64/slurm/spank_quantum.so \
    && test -x "${QFW_SLURM_PREFIX}/bin/qfw-slurm-driver" \
    && test -x /usr/lib64/slurm/spank_quantum.so \
    && test -x "${QFW_SLURM_PREFIX}/libexec/qfw-slurm/qfw-slurm-bb" \
    && test -f "${QFW_SLURM_PREFIX}/share/licenses/qfw-slurm/LICENSE" \
    && test -f "${QFW_SLURM_PREFIX}/share/man/man7/qfw-slurm.7" \
    && test -f "${QFW_SLURM_PREFIX}/share/man/man8/qfw-slurm-gateway.8" \
    && test -f "${QFW_SLURM_PREFIX}/share/man/man1/qfw-sinfo.1" \
    && test -f "${QFW_SLURM_PREFIX}/share/man/man1/qfw-squeue.1" \
    && test -f "${QFW_SLURM_PREFIX}/share/qfw-slurm/config/plugin.conf.example" \
    && "${QFW_IMAGE_VENV}/bin/python" -c \
        'import qfw_slurm_gateway, qfw_slurm_inspect' \
    && test -x "${QFW_IMAGE_VENV}/bin/qfw-sinfo" \
    && test -x "${QFW_IMAGE_VENV}/bin/qfw-squeue" \
    && rm -rf "${QFW_SLURM_SOURCE}" "${QFW_SLURM_BUILD}"

ENV QFW_IMAGE_PREFIX=${QFW_IMAGE_PREFIX} \
    QFW_IMAGE_VENV=${QFW_IMAGE_VENV} \
    QFW_PREFIX=${QFW_IMAGE_PREFIX} \
    QFW_VENV=${QFW_IMAGE_VENV} \
    QFW_SLURM_PREFIX=${QFW_SLURM_PREFIX} \
    NWQSIM_PREFIX=${NWQSIM_PREFIX} \
    TNQVM_PREFIX=${TNQVM_PREFIX} \
    QRMI_PREFIX=${QRMI_PREFIX} \
    QRMI_VERSION=${QRMI_VERSION} \
    MODULEPATH=/etc/modulefiles:/usr/share/Modules/modulefiles:/usr/share/modulefiles \
    LD_LIBRARY_PATH=${OMPI_PREFIX}/lib:${OMPI_PREFIX}/lib64:${QRMI_PREFIX}/lib:${LD_LIBRARY_PATH}

COPY modulefiles /etc/modulefiles
RUN set -ex \
    && env -i PATH=/usr/share/Modules/bin:/usr/bin:/bin \
        MODULEPATH=/etc/modulefiles:/usr/share/Modules/modulefiles \
        modulecmd sh load libfabric openmpi nwqsim \
        >/tmp/qfw-simulator-environment.sh \
    && . /tmp/qfw-simulator-environment.sh \
    && command -v prte \
    && command -v pterm \
    && command -v circuit_runner.nwqsim \
    && rm -f /tmp/qfw-simulator-environment.sh

# TJN: Add a basic cgroup.conf b/c appears to be needed now
COPY cgroup.conf /etc/slurm/cgroup.conf

COPY slurm.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf
COPY rest.conf /etc/slurm/rest.conf
COPY gres.conf /etc/slurm/gres.conf
COPY config/qfw-slurm/burst_buffer.conf /etc/slurm/burst_buffer.conf
COPY config/qfw-slurm/burst-buffer.lua.conf /etc/openqse/qfw-slurm/burst-buffer.lua.conf
COPY config/qfw-slurm/resources.lua /etc/openqse/qfw-slurm/resources.lua
COPY config/qfw-slurm/plugin.conf /etc/openqse/qfw-slurm/plugin.conf
COPY config/qfw-slurm/gateway.yaml /etc/openqse/qfw-slurm/gateway.yaml
COPY config/qfw-slurm/plugstack.conf /etc/slurm/plugstack.conf
RUN set -x \
    && groupadd -r qfw-slurm \
    && useradd -r -g qfw-slurm -d /var/lib/qfw-slurm-gateway \
        -s /sbin/nologin qfw-slurm \
    && install -o root -g root -m 0644 \
        "${QFW_SLURM_PREFIX}/share/qfw-slurm/slurm/job_submit.lua" \
        /etc/slurm/job_submit.lua \
    && install -o root -g root -m 0644 \
        "${QFW_SLURM_PREFIX}/share/qfw-slurm/slurm/burst_buffer.lua" \
        /etc/slurm/burst_buffer.lua \
    && printf '%s\n' '__QHPC_RUNTIME_SECRET__' > /etc/slurm/jwt.key \
    && sed -i 's/^StoragePass=.*/StoragePass=__QHPC_RUNTIME_SECRET__/' \
        /etc/slurm/slurmdbd.conf \
    && chown slurm:slurm /etc/slurm/slurm.conf \
    && chown slurm:slurm /etc/slurm/jwt.key \
    && chown slurm:slurm /etc/slurm/rest.conf \
    && chown slurm:slurm /etc/slurm/gres.conf \
    && chown slurm:slurm /etc/slurm/slurmdbd.conf \
    && chown root:root /etc/slurm/job_submit.lua \
        /etc/slurm/burst_buffer.lua /etc/slurm/burst_buffer.conf \
        /etc/slurm/plugstack.conf /etc/openqse/qfw-slurm/resources.lua \
        /etc/openqse/qfw-slurm/burst-buffer.lua.conf \
    && chown root:slurm /etc/openqse/qfw-slurm/plugin.conf \
    && chown root:qfw-slurm /etc/openqse/qfw-slurm/gateway.yaml \
    && chmod 0644 /etc/slurm/job_submit.lua /etc/slurm/burst_buffer.lua \
        /etc/slurm/burst_buffer.conf /etc/slurm/plugstack.conf \
        /etc/openqse/qfw-slurm/resources.lua \
    && chmod 0640 /etc/openqse/qfw-slurm/plugin.conf \
        /etc/openqse/qfw-slurm/gateway.yaml \
    && chmod 600 /etc/slurm/jwt.key \
    && chmod 600 /etc/slurm/slurmdbd.conf \
    && test -x /usr/lib64/slurm/job_submit_lua.so \
    && test -x /usr/lib64/slurm/burst_buffer_lua.so \
    && test -x /usr/lib64/slurm/spank_quantum.so \
    && test -f /etc/slurm/job_submit.lua \
    && test -f /etc/slurm/burst_buffer.lua \
    && test -f /etc/openqse/qfw-slurm/plugin.conf

RUN set -x \
    &&  useradd -r -g users --uid=1010 -m -c "Solomon Grundy" sgrundy

COPY rpm.qhpc.lock /tmp/rpm.qhpc.lock
RUN set -ex \
    && rpm -qa --qf '%{NAME}\t%{EPOCHNUM}:%{VERSION}-%{RELEASE}\t%{ARCH}\t%{LICENSE}\n' \
        | sort > /tmp/rpm.qhpc.actual \
    && diff -u /tmp/rpm.qhpc.lock /tmp/rpm.qhpc.actual \
    && install -d -m 0755 /usr/share/qhpc \
    && install -m 0644 /tmp/rpm.qhpc.lock /usr/share/qhpc/rpm-lock.tsv \
    && rm -f /tmp/rpm.qhpc.lock /tmp/rpm.qhpc.actual \
    && ! grep -R -E '(^|[[:space:]])sslverify=false' \
        /etc/dnf /etc/yum.conf 2>/dev/null

COPY source-lock.json /usr/share/qhpc/source-lock.json

COPY docker-entrypoint.qhpc.sh /usr/local/bin/docker-entrypoint.sh
COPY tools/qfw-site-services /usr/local/sbin/qfw-site-services
COPY man/man8/qfw-site-services.8 /usr/local/share/man/man8/qfw-site-services.8
RUN chmod 0755 /usr/local/bin/docker-entrypoint.sh \
        /usr/local/sbin/qfw-site-services \
    && chmod 0644 /usr/local/share/man/man8/qfw-site-services.8
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["slurmdbd"]
