// Generated by qasm3-import
// ECC: steane d=3

func.func @bell() -> (i1, i1) {
    %v0 = ftqc.init_zero : !ftqc.logical_qubit<#ftqc.ecc<steane, 3>>
    %v1 = ftqc.init_zero : !ftqc.logical_qubit<#ftqc.ecc<steane, 3>>
    %v2 = ftqc.logical_h %v0 : !ftqc.logical_qubit<#ftqc.ecc<steane, 3>>
    %v3, %v4 = ftqc.logical_cnot %v2, %v1
        : (!ftqc.logical_qubit<#ftqc.ecc<steane, 3>>, !ftqc.logical_qubit<#ftqc.ecc<steane, 3>>)
        -> (!ftqc.logical_qubit<#ftqc.ecc<steane, 3>>, !ftqc.logical_qubit<#ftqc.ecc<steane, 3>>)
    %b0 = ftqc.logical_measure %v3
        : (!ftqc.logical_qubit<#ftqc.ecc<steane, 3>>) -> i1
    %b1 = ftqc.logical_measure %v4
        : (!ftqc.logical_qubit<#ftqc.ecc<steane, 3>>) -> i1
    func.return %b0, %b1 : i1, i1
}
